// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Netfritz.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Netfritz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Netfritz.Core.Entities.AdministradorEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("Netfritz.Core.Entities.ClienteEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Cartao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Netfritz.Core.Entities.CompraEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ClienteId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FitaId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("FitaId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Netfritz.Core.Entities.FitaEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Fitas");
                });

            modelBuilder.Entity("Netfritz.Core.Entities.CompraEntity", b =>
                {
                    b.HasOne("Netfritz.Core.Entities.ClienteEntity", "Cliente")
                        .WithOne("Compra")
                        .HasForeignKey("Netfritz.Core.Entities.CompraEntity", "ClienteId");

                    b.HasOne("Netfritz.Core.Entities.FitaEntity", "Fita")
                        .WithMany()
                        .HasForeignKey("FitaId");

                    b.OwnsOne("Netfritz.Core.Entities.Avaliacao", "Avaliacao", b1 =>
                        {
                            b1.Property<string>("CompraEntityId")
                                .HasColumnType("text");

                            b1.Property<string>("Comentario")
                                .HasColumnType("text");

                            b1.Property<int>("Nota")
                                .HasColumnType("integer");

                            b1.HasKey("CompraEntityId");

                            b1.ToTable("Compras");

                            b1.WithOwner()
                                .HasForeignKey("CompraEntityId");
                        });

                    b.Navigation("Avaliacao");

                    b.Navigation("Cliente");

                    b.Navigation("Fita");
                });

            modelBuilder.Entity("Netfritz.Core.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Compra");
                });
#pragma warning restore 612, 618
        }
    }
}
